version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - ./backend/todos.db:/app/todos.db
    environment:
      - NODE_ENV=production
